Fix InterruptVectorDefault() for CH32V10x, CH32V20x and CH32V30x
cnlohr/ch32v003fun pull request #425
Opened 2024-10-21 21:26 UTC by hexaedron

Fix for #424

2024-10-26 20:15 UTC, AlexanderMandera requested changes

2024-10-26 20:15 UTC, AlexanderMandera commented on ch32v003fun/ch32v003fun.c
> +void USBFS_IRQHandler( void ) 			__attribute__((section(".text.vector_handler"))) __attribute((weak,alias("DefaultIRQHandler"))) __attribute__((used));
Renaming `USBHS_IRQHandler` breaks the existing V30x USB HS example (see extralibs/hsusb_v30x.c).
For D8 (I think which is the no high-speed version), there is only a single USBFS_IRQHandler with no wakeup handler.
For D8C (like 305/307) there is both USBFS_IRQHandler, USBHS_IRQHandler and USBHSWakeup_IRQHandler.

2024-10-26 20:15 UTC, AlexanderMandera commented on ch32v003fun/ch32v003fun.c
> +	.word   USBFSWakeup_IRQHandler     /* USBHS Wakeup */ \n \
```suggestion
	.word   USBHSWakeup_IRQHandler     /* USBHS Wakeup */ \n \
```

2024-10-26 20:15 UTC, AlexanderMandera commented on ch32v003fun/ch32v003fun.c
> +	.word   USBFS_IRQHandler           /* USBHS */ \n \
```suggestion
	.word   USBHS_IRQHandler           /* USBHS */ \n \
```

2024-10-26 20:15 UTC, AlexanderMandera commented on ch32v003fun/ch32v003fun.c
> +void USBFSWakeup_IRQHandler( void )		__attribute__((section(".text.vector_handler"))) __attribute((weak,alias("DefaultIRQHandler"))) __attribute__((used));
```suggestion
void USBFS_IRQHandler( void ) 			__attribute__((section(".text.vector_handler"))) __attribute((weak,alias("DefaultIRQHandler"))) __attribute__((used));
void USBHSWakeup_IRQHandler( void )		__attribute__((section(".text.vector_handler"))) __attribute((weak,alias("DefaultIRQHandler"))) __attribute__((used));
```

2024-10-26 20:15 UTC, AlexanderMandera commented on ch32v003fun/ch32v003fun.c
> +void USBFS_IRQHandler( void ) 			__attribute__((section(".text.vector_handler"))) __attribute((weak,alias("DefaultIRQHandler"))) __attribute__((used));
```suggestion
void USBHS_IRQHandler( void ) 			__attribute__((section(".text.vector_handler"))) __attribute((weak,alias("DefaultIRQHandler"))) __attribute__((used));
```

2024-10-26 20:15 UTC, AlexanderMandera commented on ch32v003fun/ch32v003fun.c
> +    	.word   0 \n \
Removing the additional tab indent here should fix some of the unnecessary diff changes.

2024-11-06 06:19 UTC, cnlohr commented
Merging but I will go back later and algebra out the interrupt table.

2024-11-06 06:19 UTC, merged